# Generated by Django 2.2.7 on 2019-11-09 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latinName', models.CharField(blank=True, max_length=120, null=True)),
                ('reptiletype', models.CharField(blank=True, choices=[('X', 'Choose type of reptile'), ('C', 'Crocodile'), ('L', 'Lizard'), ('S', 'Snake'), ('T', 'Turtle')], default='X', max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('cites', models.CharField(blank=True, choices=[('X', 'Cites of animal'), ('A', 'Cites A or I'), ('B', 'Cites B or II'), ('C', 'Cites C or III'), ('D', 'Cites D or none')], default='X', max_length=1, null=True)),
                ('habitat', models.CharField(blank=True, max_length=120, null=True)),
                ('feeding', models.TextField(blank=True, max_length=500, null=True)),
                ('enclosure', models.TextField(blank=True, max_length=500, null=True)),
                ('temperature', models.TextField(blank=True, max_length=300, null=True)),
                ('sex', models.TextField(blank=True, max_length=500, null=True)),
                ('male', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female', models.ImageField(blank=True, null=True, upload_to='images')),
                ('breeding', models.TextField(blank=True, max_length=500, null=True)),
                ('incubation', models.TextField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('animalpictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.Animal')),
            ],
        ),
    ]
