# Generated by Django 2.2.7 on 2019-11-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='author',
        ),
    ]
