# Generated by Django 2.2.7 on 2019-11-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_animal_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalimages',
            old_name='image',
            new_name='images',
        ),
    ]
