# Generated by Django 2.2.7 on 2019-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_animal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='title',
        ),
        migrations.AddField(
            model_name='animal',
            name='heating',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='lighting',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
