# Generated by Django 2.2.7 on 2019-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20191123_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='reptiletype',
            field=models.CharField(blank=True, choices=[('X', 'Choose type of reptile'), ('Crocodile', 'Crocodile'), ('Lizard', 'Lizard'), ('Snake', 'Snake'), ('Turtle', 'Turtle')], default='X', max_length=1, null=True),
        ),
    ]
