# Generated by Django 2.2.7 on 2019-12-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20191226_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='handling',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
