# Generated by Django 2.2.7 on 2019-12-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_animal_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='disseases',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='health',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
