# Generated by Django 2.2.7 on 2019-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20191226_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
