# Generated by Django 2.2.7 on 2019-12-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20191227_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='reptiletype',
            field=models.CharField(blank=True, choices=[('X', 'Choose type of reptile'), ('C', 'Crocodile'), ('L', 'Lizard'), ('S', 'Snake'), ('T', 'Turtle')], default='X', max_length=1, null=True),
        ),
    ]
