# Generated by Django 2.2.7 on 2019-12-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20191227_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
